const el=id=>document.getElementById(id);let current=null;let sequence=0;
function save(blob,name){const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
async function check(scenario){const serial=++sequence;el('activity').textContent='Checking the actual source and replaying the result…';el('package').disabled=true;el('staging').disabled=true;el('download').disabled=true;try{const response=await fetch('/api/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario})});const data=await response.json();if(!response.ok)throw Error(data.error);if(serial!==sequence)return;current=data;document.querySelectorAll('.revision').forEach(b=>b.classList.toggle('active',b.dataset.scenario===scenario));el('revision-title').textContent=data.title;el('before-code').textContent=data.original_source;el('after-code').textContent=data.source;el('tests-pill').textContent=`${data.ordinary_tests.passed}/${data.ordinary_tests.total} passed`;el('test-cases').replaceChildren();for(const row of data.ordinary_tests.cases){const div=document.createElement('div');div.className='test-row';const code=document.createElement('code');code.textContent=`units=${row.arguments.units}, price=${row.arguments.unit_price}, shipping=${row.arguments.shipping}`;const status=document.createElement('span');status.textContent=row.passed?'✓ passed':'failed';div.append(code,status);el('test-cases').append(div);}const receipt=data.receipt;const result=receipt.results[0];const passed=receipt.status==='PASS';el('gate-title').textContent=passed?'The behavior is preserved.':'The release stays blocked.';el('verdict').classList.toggle('blocked',!passed);el('verdict-icon').textContent=passed?'✓':'×';el('verdict-name').textContent=passed?'Proved equivalent':result.status==='REFUTED'?'Meaning changed':'Unsupported program';el('verdict-description').textContent=passed?'The coefficient residual is exactly zero for every integer input.':result.status==='REFUTED'?'The ordinary tests pass, but this revision changes the billing contract.':result.reason;el('witness').hidden=!result.counterexample;if(result.counterexample){el('witness-values').replaceChildren();for(const [key,value] of Object.entries(result.counterexample)){const item=document.createElement('div');const dt=document.createElement('dt');dt.textContent=key;const dd=document.createElement('dd');dd.textContent=String(value);item.append(dt,dd);el('witness-values').append(item);}el('expected-total').textContent=result.expected_at_counterexample;el('actual-total').textContent=result.actual_at_counterexample;}el('receipt-id').textContent=receipt.receipt_id;el('replay-result').textContent='✓ Recomputed from current source, contract, and checker';el('evidence-json').textContent=JSON.stringify(receipt,null,2);el('package').disabled=!passed;el('staging').disabled=!passed;el('download').disabled=false;el('activity').textContent=passed?'Verified packaging is available. Human release remains a separate decision.':'No package can be produced from this receipt.';}catch(error){el('activity').textContent=error.message;}}
document.querySelectorAll('.revision').forEach(button=>button.addEventListener('click',()=>check(button.dataset.scenario)));
el('download').addEventListener('click',()=>{if(current)save(new Blob([JSON.stringify(current.receipt,null,2)],{type:'application/json'}),`evidencegate-${current.scenario}.json`);});
el('package').addEventListener('click',async()=>{if(!current)return;el('package').disabled=true;try{const response=await fetch('/api/package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario:current.scenario})});if(!response.ok){const data=await response.json();throw Error(data.error);}save(await response.blob(),'verified-billing.zip');el('activity').textContent='Verified package created with the checked source and its evidence receipt.';}catch(error){el('activity').textContent=error.message;}finally{el('package').disabled=current.receipt.status!=='PASS';}});
check('original');

el('staging').addEventListener('click',async()=>{if(!current)return;el('staging').disabled=true;el('activity').textContent='Starting the actual package and checking billing, source drift, and recovery…';try{const response=await fetch('/api/staging',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario:current.scenario})});const result=await response.json();if(!response.ok)throw Error(result.error);el('activity').textContent=`${result.checks_passed} staging checks passed: ${result.billing_canaries} billing canaries, source drift blocked, recovery verified. Human release remains required.`;el('evidence-json').textContent=JSON.stringify(result,null,2);}catch(error){el('activity').textContent=error.message;}finally{el('staging').disabled=current.receipt.status!=='PASS';}});
